services:
  app:
    container_name: homework_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - FLASK_ENV=production
    restart: unless-stopped
