version: '3.8'
services:
  app:
    container_name: homework_app
    build:
      context: ../app
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  api:
    container_name: homework_api
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
