version: '3.8'
services:
  homework-app:
    container_name: homework_app
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - ../app/src:/usr/src/app/src
    ports:
      - "5173:5173"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
  homework-api:
    container_name: homework_api
    build:
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
  homework-proxy:
    container_name: homework_proxy
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - 2121:8080
    depends_on:
      - homework-api
      - homework-app
    restart: unless-stopped
