version: '3.8'
services:
  app:
    container_name: homework_app
    build:
      context: ../app
      dockerfile: Dockerfile
      target: dev
    command: pnpm run dev --host
    volumes:
      - ../app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
  api:
    container_name: homework_api
    build:
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
