version: '3.8'
services:
  app:
    container_name: homework_app
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - ../app/src:/usr/src/app/src
    ports:
      - "5173:5173"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
  api:
    container_name: homework_api
    build:
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api:/workspace/api
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
