version: '3.8'
services:
  homework-app:
    container_name: homework_app
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  homework-api:
    container_name: homework_api
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  homework-proxy:
    container_name: homework_proxy
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - 2121:8080
    depends_on:
      - homework-api
      - homework-app
    restart: unless-stopped
